name: spotify-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - sqlalchemy
  - psycopg2
  - pyqt=5
  - pip
  - pip:
      - spotipy
      - gspread
      - python-telegram-bot>=20.0
      - pytest-asyncio
